#+title: Defensive Security 
#+author: mouse

Blue Team

User cyber security awareness: 
- Training users about cyber security helps protect against various attacks that target their systems.
Documenting and managing assets: 
- We need to know the types of systems and devices that we have to manage and protect properly.
Updating and patching systems: 
- Ensuring that computers, servers, and network devices are correctly updated and patched against any known vulnerability (weakness).
Setting up preventative security devices: 
- firewall and intrusion prevention systems (IPS) are critical components of preventative security. Firewalls control what network traffic can go inside and what can leave the system or network. IPS blocks any network traffic that matches present rules and attack signatures.
Setting up logging and monitoring devices: 
- Without proper logging and monitoring of the network, it won’t be possible to detect malicious activities and intrusions. If a new unauthorized device appears on our network, we should be able to know.

** Security Operations Center (SOC)
- Areas of Interest 
  + Vulnerabilities
    - fix, patch, remediate 
  + Policy Violations 
    - Sec policy rules 
  + Unauthorized Activity
    - Detect events, block and prevent 
  + Network Instrusions 
    - Detect and prevent further damage 
- Threat Intelligence
  + Information gathering of potential and actual threats, achieve *threat informed defense* 
  + Porcess, analyze Data 
  + determine actionable steps 
  + know their tactics, techniques and procedures 
  + identify, predict and mitigate 
- Digital Forensics and Incident Response (DFIR)
  + Investigating crimes and establishing facts 
  + analyzing evidence of an attack
  + determine perpertrators
  + File System 
    - Analyzing digital foresnics image ( low level copy ) of a systems storage 
    - find deleted files, created files, partially over written files 
  + System Memory 
    - forsenic image of system memory, analyze contents and learn about attack 
  + System Logs 
    - check for traces of activity 
  + Network logs 
    - Logs of network packets, detecting attack 
- Incident Response 
  + Major phases of incident response process 
    - Preperation
      + requires team to be trained to handle incidents, measures put in place to prevent incidents 
    - Detection and Analysis
      + Team has resources to detect incident
      + essential to analyze detected incidents to determine/learn of severity
    - Containment, Eradication, and Recovery 
      + Once an incident is detected, crucial to stop further affect on systems
      + Eliminate it and recover affected systems
      + EX: Virus, stop and contain from spreading and clean(eradicate) to ensure proper system recovery. 
    - Post Incident Activity 
      + After successful recovery, report is produced and lesson learned is shared to prevent similar future incidents 
- Malware Analysis
  + Virus
    - Attaches itself to program, is designed to spread, alters, overwrites and eletes files 
  + Trojan Horse 
    - shows desirable functions but hides malcious function ( RATs )
  + Ransomware 
    - encrypts user files, demands cash 
  + Types of Analysis
    - Static
      + Inspecting the malicious program without running, involves knowledge of asm usually 
    - Dynamic 
      + Works by running in controlled environment and monitoring its activites 

* Tools 
Security Information and Event Management (SIEM) system

AbuseIPDB, and Cisco Talos Intelligence

Hushed and Burner - Phone privacy apps 
* Roles 
** Security Analyst 
Security analysts are integral to constructing security measures across organisations to protect the company from attacks. Analysts explore and evaluate company networks to uncover actionable data and recommendations for engineers to develop preventative measures. This job role requires working with various stakeholders to gain an understanding of security requirements and the security landscape.

*** Responsibilities
Working with various stakeholders to analyse the cyber security throughout the company
Compile ongoing reports about the safety of networks, documenting security issues and measures taken in response
Develop security plans, incorporating research on new attack tools and trends, and measures needed across teams to maintain data security.

** Security Engineers
Security engineers develop and implement security solutions using threats and vulnerability data - often sourced from members of the security workforce. Security engineers work across circumventing a breadth of attacks, including web application attacks, network threats, and evolving trends and tactics. The ultimate goal is to retain and adopt security measures to mitigate the risk of attack and data loss.

*** Responsibilities
Testing and screening security measures across software
Monitor networks and reports to update systems and mitigate vulnerabilities
Identify and implement systems needed for optimal security

** Incident Responders 
Incident responders respond productively and efficiently to security breaches. Responsibilities include creating plans, policies, and protocols for organisations to enact during and following incidents. This is often a highly pressurised position with assessments and responses required in real-time, as attacks are unfolding. Incident response metrics include MTTD, MTTA, and MTTR - the meantime to detect, acknowledge, and recover (from attacks.) The aim is to achieve a swift and effective response, retain financial standing and avoid negative breach implications. Ultimately, incident responders protect the company's data, reputation, and financial standing from cyber attacks.

*** Responsibilities
Developing and adopting a thorough, actionable incident response plan
Maintaining strong security best practices and supporting incident response measures
Post-incident reporting and preparation for future attacks, considering learnings and adaptations to take from incidents

** Digital Forensics Examiner 
If you like to play detective, this might be the perfect job. If you are working as part of a law-enforcement department, you would be focused on collecting and analysing evidence to help solve crimes: charging the guilty and exonerating the innocent. On the other hand, if your work falls under defending a company's network, you will be using your forensic skills to analyse incidents, such as policy violations.

*** Responsibilities
Collect digital evidence while observing legal procedures
Analyse digital evidence to find answers related to the case
Document your findings and report on the case

** Malware Analyst 
A malware analyst's work involves analysing suspicious programs, discovering what they do and writing reports about their findings. A malware analyst is sometimes called a reverse-engineer as their core task revolves around converting compiled programs from machine language to readable code, usually in a low-level language. This work requires the malware analyst to have a strong programming background, especially in low-level languages such as assembly language and C language. The ultimate goal is to learn about all the activities that a malicious program carries out, find out how to detect it and report it.

*** Responsibilities
Carry out static analysis of malicious programs, which entails reverse-engineering
Conduct dynamic analysis of malware samples by observing their activities in a controlled environment
Document and report all the findings

* Concepts 
** Security Frameworks 

*** NIST Cybersecurity Framework (1.1)
- https://www.nist.gov/cyberframework
- popular framework used to improve orgs standards and manage risk 
- provides guidelines on sec controls, benchmarks for success of orgs from critical infrastructure to comercial 
- Limited section on standard guideline for methodology a pentester should take 
- Advantages 
  + NIST Framework is estimated to be used by 50% of American Orgs 
  + Framework is extremely detailed in setting standards to help organisations mitigate threats 
  + Framework is frequently updated 
  + NIST provides accrediation for organizations that use this framework 
  + NIST framework is designed to be implemented alongside other frame works 
- Disadvantages 
  + NIST has many iterations of frameworks - which one applies ?!?! 
  + NIST framework has weak auditing policies, making it difficult to determine how a breach occured 
  + Framework does not consider cloud computing - which is popular 

** CIA Triad 
- if one element is not met then the other two are rendered useless 
- Confidentiality
- Integrity
  + Hash Verifications
  + Digital Signatures 
- Availability
  + Redundancy 
  + Sec protocols for technology and services  

** PIM ( Privileged Identity Management ) and PAM ( Privileged Access Management )
The levels of access given to individuals are determined on two primary factors:
- the individual's role/function within the organization
- the sensitivity of the information being stored on the system 
- PIM is used to translates a user's role within an organization into an access role on the system 
- PAM is the management of the privileges a systems access role has, among other things 
- principle of least privilege, users should be given the minimum amount of privileges 
  and only those that are absolutely necessary for them to perform their duties
  other people should be able to trust what people write to 
- PAM also encompasses enforcing security policies such as password management, auding policies and reducing the attack surface a system faces 

** Security Models 

*** The Bell-La Padula Model 
- used to achieve confidentiality 
- assumes hierarchial structure where everyones responsibilites/roles are well defined 
- Works by granting access to pieces of data called objects on need to know basis 
- "No write down, no read up"
- popular within orgs such as governmental and military due to vetting, applicants are assumed to be trustworthy 
**** Advantages
- Policies in this model can be replicated to real-life orgs hierarchies 
- Simple to implement and understand - proven successful 
**** Disadvantages
- Even though a user may not have access to an object, they will know about its existence 
- The model relies on a large amount of trust within the organisation 

*** Biba Model 
- Equivalent of the Bell-La Padula model but for the integrity of the CIA Triad 
- Applies the rules to objects (data) and subjects (users)
- "No write up, no read down"
- subjects can create or write content to objects at or below their level
- can only read the contents of objects above the subjects level 
- Used in organizations or situations where integrity is more important than confidentiality, ex software development 
**** Advantages 
- This model is simple to implement 
- Resolves the limitations of the Bell-La-Padula model by addressing both confidentiality and data integrity 
**** Disadvantages 
- There will be many levels of access and objects. Things can be easily overlooked when apply security controls. 
- Often results in delays within a business. For example, a doctor would not be able to read the notes made by a nurse in a hospital with this model.

** Attack Prevention 
**** RFI and LFI Avoidance 
Keep system and services, including web application frameworks, updated with the latest version.
Turn off PHP errors to avoid leaking the path of the application and other potentially revealing information.
A Web Application Firewall (WAF) is a good option to help mitigate web application attacks.
Disable some PHP features that cause file inclusion vulnerabilities if your web app doesn't need them, such as allow_url_fopen on and allow_url_include.
Carefully analyze the web application and allow only protocols and PHP wrappers that are in need.
Never trust user input, and make sure to implement proper input validation against file inclusion.
Implement whitelisting for file names and locations as well as blacklisting.
**** SSRF
Avoiding Server-Sider Request Forgery  
- Deny List
  + All request are accepted apart from resources specified 
  + Restrict access to localhost 
  + 0, 0.0.0.0, 0000, 127.1, 127.*.*.*, 2130706433, 017700000001
  + subdomains that have a DNS record which resolves to the IP Address 127.0.0.1 such as 127.0.0.1.nip.io
  + Block access to IP Address for metadata of Cloud server 169.254.169.254
- Allow List 
  + opposite of deny list duh 
  + uch as a rule that an URL used in a parameter must begin with https://website.thm. An attacker could quickly circumvent this rule by creating a subdomain on an attacker's domain name, such as https://website.thm.attackers-domain.thm
- Open Redirect 
  + Open redirect is an endpoint on the server where the website vistor gets automatically redirected - 301 
  + This could be exploited to redirect internel request to domain of choice 

