- name: Upgrade girlboss
  hosts: girlboss
  vars_files:
    - hidden_vars.yml
  vars:
    ansible_become_pass: "{{ girlboss_become_pass }}"
  tasks:
    - name: upgrade packages
      become: yes
      ansible.builtin.apt:
        upgrade: yes
        update_cache: yes
    - name: upgrade pleroma
      become: yes
      ansible.builtin.script:
        cmd: update_pleroma
    - name: restart pleroma
      become: yes
      ansible.builtin.systemd_service:
        name: pleroma.service
        state: restarted
